const RANKS = [
  {
    id: "F",
    name: "F-Rank",
    subtitle: "Пробуждение",
    weeks: "1–2",
    color: "#6b7280",
    glow: "rgba(107,114,128,0.4)",
    exercises: [
      { id: "pushups", name: "Отжимания", target: 10, icon: "💪" },
      { id: "squats", name: "Приседания", target: 15, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 15, icon: "🔥" },
      { id: "walk_km", name: "Ходьба (км)", target: 2, icon: "🚶", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 20, icon: "⏱️", step: 5 },
    ],
  },
  {
    id: "E",
    name: "E-Rank",
    subtitle: "Адаптация",
    weeks: "3–4",
    color: "#22c55e",
    glow: "rgba(34,197,94,0.4)",
    exercises: [
      { id: "pushups", name: "Отжимания", target: 20, icon: "💪" },
      { id: "squats", name: "Приседания", target: 25, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 25, icon: "🔥" },
      { id: "walk_km", name: "Ходьба/бег (км)", target: 3, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 30, icon: "⏱️", step: 5 },
    ],
  },
  {
    id: "D",
    name: "D-Rank",
    subtitle: "Становление",
    weeks: "5–6",
    color: "#3b82f6",
    glow: "rgba(59,130,246,0.4)",
    exercises: [
      { id: "pushups", name: "Отжимания", target: 35, icon: "💪" },
      { id: "squats", name: "Приседания", target: 40, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 40, icon: "🔥" },
      { id: "walk_km", name: "Бег (км)", target: 4, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 45, icon: "⏱️", step: 5 },
      { id: "lunges", name: "Выпады (на ногу)", target: 15, icon: "🦿" },
    ],
  },
  {
    id: "C",
    name: "C-Rank",
    subtitle: "Рост силы",
    weeks: "7–8",
    color: "#a855f7",
    glow: "rgba(168,85,247,0.4)",
    exercises: [
      { id: "pushups", name: "Отжимания", target: 50, icon: "💪" },
      { id: "squats", name: "Приседания", target: 60, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 60, icon: "🔥" },
      { id: "walk_km", name: "Бег (км)", target: 6, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 60, icon: "⏱️", step: 5 },
      { id: "lunges", name: "Выпады (на ногу)", target: 25, icon: "🦿" },
    ],
  },
  {
    id: "B",
    name: "B-Rank",
    subtitle: "Daily Quest",
    weeks: "9–10",
    color: "#f59e0b",
    glow: "rgba(245,158,11,0.4)",
    exercises: [
      { id: "pushups", name: "Отжимания", target: 75, icon: "💪" },
      { id: "squats", name: "Приседания", target: 80, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 80, icon: "🔥" },
      { id: "walk_km", name: "Бег (км)", target: 8, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 90, icon: "⏱️", step: 5 },
      { id: "lunges", name: "Выпады (на ногу)", target: 35, icon: "🦿" },
      { id: "pullups", name: "Подтягивания", target: 10, icon: "🏋️" },
    ],
  },
  {
    id: "A",
    name: "A-Rank",
    subtitle: "Shadow Monarch",
    weeks: "11–12",
    color: "#ef4444",
    glow: "rgba(239,68,68,0.5)",
    exercises: [
      { id: "pushups", name: "Отжимания (усл.)", target: 100, icon: "💪" },
      { id: "squats", name: "Пистолетики (на ногу)", target: 100, icon: "🦵" },
      { id: "crunches", name: "Скручивания", target: 100, icon: "🔥" },
      { id: "walk_km", name: "Бег интервальный (км)", target: 10, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 120, icon: "⏱️", step: 5 },
      { id: "lunges", name: "Выпады с весом (на ногу)", target: 40, icon: "🦿" },
      { id: "pullups", name: "Подтягивания", target: 20, icon: "🏋️" },
    ],
  },
  {
    id: "S",
    name: "S-Rank",
    subtitle: "National Level Hunter",
    weeks: "∞",
    color: "#ffd700",
    glow: "rgba(255,215,0,0.5)",
    exercises: [
      { id: "pushups", name: "Алмазные отжимания", target: 150, icon: "💪" },
      { id: "squats", name: "Пистолетики (на ногу)", target: 150, icon: "🦵" },
      { id: "crunches", name: "Скручивания с весом", target: 150, icon: "🔥" },
      { id: "walk_km", name: "Бег (км)", target: 15, icon: "🏃", step: 0.5 },
      { id: "plank_sec", name: "Планка (сек)", target: 180, icon: "⏱️", step: 5 },
      { id: "lunges", name: "Выпады с весом (на ногу)", target: 50, icon: "🦿" },
      { id: "pullups", name: "Подтягивания с весом", target: 30, icon: "🏋️" },
    ],
  },
];

export default RANKS;
